### ISSUE TITLE
There is no visual tool in the file.

### ISSUE THREAD

**Issue by shuentang** [predict-idlab/sleep-linear#1]
There are not find those:
    from ml_tools.visualizations.models_linear import plot_linear_classification_coefs
    from ml_tools.visualizations.models import plot_learning_curve
    from ml_tools.visualizations.evaluation import plot_confusion_matrix

I guess they're in the "../../ML_tools/src/" folder, but I can't find it.
Could you please upload it?

**Comment by jvdd** [comment]
Thx for pointing out! I'll add the code to the `src` folder and update the imports in the notebooks.

**Comment by jvdd** [comment]
@shuentang  this should now be fixed in the latest commit! The missing code is added to the [`src/visualizations.py`](https://github.com/predict-idlab/sleep-linear/blob/main/src/visualizations.py) file

Let me know if this works for you? :)

**Comment by shuentang** [comment]
> 
Thank you very much !   
 I get it!
